---
# tasks file for task17
#
- name: Shared - clone Git repo
  git:
    repo: https://github.com/ArtemTabolich/Task-16.git
    dest: /task17/dockerT17

- name: Shared - enable services
  service:
    name: docker
    enabled: true
    state: started

- name: Shared - install or Upgrade urllib3
  pip:
    name: urllib3==1.25.11
    state: present

- name: Shared - install Docker SDK for Python
  pip:
    name:
      - docker==6.1.3
      - docker-compose

- name: Shared - build docker-compose
  community.docker.docker_compose:
    project_src: /task17/dockerT17/
    files:
      - docker-compose.yml
